# Generated by Django 5.0.3 on 2024-06-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descriptions',
            new_name='description',
        ),
    ]
